In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time
import pickle
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE

In [2]:
def selectkbest(indep_x,dep_y,n):
    test=SelectKBest(score_func=chi2,k=n)
    fit1=test.fit(indep_x,dep_y)
    selectk_features=fit1.transform(indep_x)
    return selectk_features

In [3]:
def split_scaler(indep_x,dep_y):
    from sklearn.model_selection import train_test_split
    from sklearn.preprocessing import StandardScaler
    x_train,x_test,y_train,y_test=train_test_split(indep_x,dep_y,test_size=0.25,random_state=42)
    sc=StandardScaler()
    x_train=sc.fit_transform(x_train)
    x_test=sc.transform(x_test)
    return x_train,x_test,y_train,y_test

In [4]:
def cm_prediction(classifier,x_test):
    y_pred=classifier.predict(x_test)
    from sklearn.metrics import confusion_matrix
    cm=confusion_matrix(y_test,y_pred)
    from sklearn.metrics import classification_report
    report=classification_report(y_test,y_pred)
    from sklearn.metrics import accuracy_score
    Accuracy=accuracy_score(y_test,y_pred)
    return classifier,Accuracy,report,cm,x_test,y_test

In [5]:
def logistic(x_train,y_train,x_test):
    from sklearn.linear_model import LogisticRegression
    from sklearn.model_selection import GridSearchCV
    param_grid={'solver':['lbfgs','newton-cg','liblinear']}
    classifier=GridSearchCV(LogisticRegression(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
    classifier.fit(x_train,y_train)
    classifier,Accuracy,report,cm,x_test,y_test=cm_prediction(classifier,x_test)
    return classifier,Accuracy,report,cm,x_test,y_test

In [6]:
def svc(x_train,y_train,x_test):
    from sklearn.svm import SVC
    from sklearn.model_selection import GridSearchCV
    param_grid={'kernel':['rbf','linear','poly'],'gamma':['auto','scale']}
    classifier=GridSearchCV(SVC(probability=True),param_grid,verbose=3,n_jobs=-1,scoring='f1_weighted')
    classifier.fit(x_train,y_train)
    classifier,Accuracy,report,cm,x_test,y_test=cm_prediction(classifier,x_test)
    return classifier,Accuracy,report,cm,x_test,y_test

In [7]:
def Decision(x_train,y_train,x_test):
    from sklearn.tree import DecisionTreeClassifier
    from sklearn.model_selection import GridSearchCV
    param_grid={'criterion':['gini','entropy','log_loss'],'splitter':['best','random']}
    classifier=GridSearchCV(DecisionTreeClassifier(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
    classifier.fit(x_train,y_train)
    classifier,Accuracy,report,cm,x_test,y_test=cm_prediction(classifier,x_test)
    return classifier,Accuracy,report,cm,x_test,y_test

In [8]:
def random(x_train,y_train,x_test):
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.model_selection import GridSearchCV
    param_grid={'criterion':['gini','entropy','log_loss'],'max_features':['sqrt','log2'],'n_estimators':[100]}
    classifier=GridSearchCV(RandomForestClassifier(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
    classifier.fit(x_train,y_train)
    classifier,Accuracy,report,cm,x_test,y_test=cm_prediction(classifier,x_test)
    return classifier,Accuracy,report,cm,x_test,y_test

In [9]:
def selectk_classification(acclog,accsvc,accdt,accrf):
    selectk_dataframe=pd.DataFrame(index=['chisquare'],columns=['Logistic','SVC','DecisionTree','RandomForest'])
    for number,idex in enumerate(selectk_dataframe.index):
        selectk_dataframe['Logistic'][idex]=acclog[number]
        selectk_dataframe['SVC'][idex]=accsvc[number]
        selectk_dataframe['DecisionTree'][idex]=accdt[number]
        selectk_dataframe['RandomForest'][idex]=accrf[number]
    return selectk_dataframe

In [10]:
dataset=pd.read_csv("preprocessed ILPD.csv")
df=dataset
df=pd.get_dummies(df,dtype=int,drop_first=True)
df

,Age,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,A/G Ratio,Selector,Gender_Male
0,65,0.7,0.10,187.00,16.0,18,6.8,3.3,0.90,1,0
1,62,5.3,2.95,481.75,64.0,100,7.5,3.2,0.74,1,1
2,62,5.3,2.95,481.75,60.0,68,7.0,3.3,0.89,1,1
3,58,1.0,0.40,182.00,14.0,20,6.8,3.4,1.00,1,1
4,72,3.9,2.00,195.00,27.0,59,7.3,2.4,0.40,1,1
...,...,...,...,...,...,...,...,...,...,...,...
578,60,0.5,0.10,481.75,20.0,34,5.9,1.6,0.37,0,1
579,40,0.6,0.10,98.00,35.0,31,6.0,3.2,1.10,1,1
580,52,0.8,0.20,245.00,48.0,49,6.4,3.2,1.00,1,1
581,31,1.3,0.50,184.00,29.0,32,6.8,3.4,1.00,1,1
582,38,1.0,0.30,216.00,21.0,24,7.3,4.4,1.50,0,1

In [11]:
indep_x=df.drop('Selector',axis=1)
dep_y=df['Selector']
indep_x.shape
dep_y.shape
print(indep_x.shape)
print(type(indep_x))

(583, 10)
<class 'pandas.core.frame.DataFrame'>

In [14]:
kbest=selectkbest(indep_x,dep_y,5)
acclog=[]
accsvc=[]
accdt=[]
accrf=[]
x_train, x_test, y_train, y_test=split_scaler(kbest,dep_y) 
x_train, x_test, y_train, y_test

(array([[ 1.07637252, -0.68881048,  0.29990792,  1.10970864,  2.11147647],
        [ 1.14090466,  2.03006912,  2.1229076 ,  2.04762906, -0.00471511],
        [ 0.56011538, -0.20545411, -0.64923835, -0.13076675, -0.1346567 ],
        ...,
        [-0.47239892, -0.74923003, -0.12903319,  1.44251911, -0.22747212],
        [-1.76304178, -0.87006912, -0.39369897, -0.61485471, -0.84005389],
        [-1.76304178, -0.62839094, -0.22942366, -0.37281073, -0.39453987]]),
 array([[-1.63397749, -0.3262932 , -0.64923835, -1.06868717, -0.74723847],
        [-2.08570249, -0.56797139,  2.1229076 ,  2.07032068,  0.77493442],
        [ 1.01184038,  2.03006912, -0.32068772,  2.07032068,  2.11147647],
        [-0.1497382 , -0.87006912, -0.79526086,  2.07032068,  0.77493442],
        [-0.27880249,  2.03006912,  0.99351481,  0.05076623,  0.16235265],
        [-0.73052749, -0.74923003,  0.06262135, -0.82664319, -0.67298613],
        [-1.31131678, -0.74923003, -0.55797429, -1.12919816, -1.04424781],
        [ 1.01184038, -0.74923003, -0.7131232 , -0.52408822, -0.74723847],
        [-1.69850964, -0.68881048, -0.45758382, -0.43332173, -0.65442305],
        [ 1.46356538,  0.15706317, -0.46671022, -0.19127775, -0.50591838],
        [-0.1497382 , -0.68881048, -0.46671022, -0.58459921, -0.87718006],
        [-1.63397749, -0.74923003, -0.5762271 ,  2.07032068,  2.11147647],
        [ 0.36651895, -0.74923003, -0.52146866, -0.91740968, -0.95143239],
        [ 1.26996895, -0.50755184, -0.439331  , -0.91740968, -0.87718006],
        [ 0.68917966,  2.03006912,  2.1229076 , -0.00974476, -0.17178286],
        [ 1.33450109,  1.78839093, -0.53972148, -0.46357722,  0.08810031],
        [ 1.91529038, -0.62839094, -0.13815959, -0.97792068, -0.87718006],
        [ 1.20543681, -0.87006912, -0.7222496 , -0.82664319, -0.7101123 ],
        [ 2.94780467, -0.50755184, -0.31156131, -0.07025576,  1.25757461],
        [ 1.97982252,  0.58      , -0.2841821 , -0.46357722, -0.54304455],
        [ 0.04385823,  0.15706317, -0.36631975, -0.7056212 , -0.85861697],
        [ 1.65716181, -0.62839094, -0.26592928,  0.14153272,  0.53361433],
        [ 1.14090466,  2.03006912,  2.1229076 ,  0.35332121,  0.03241106],
        [ 1.85075824, -0.08461502, -0.26592928, -0.85689869, -0.43166604],
        [ 1.97982252, -0.08461502,  1.42245591,  0.92817566, -0.30172445],
        [ 0.81824395, -0.74923003, -0.37544616, -0.40306623,  0.5707405 ],
        [-0.1497382 ,  2.03006912,  0.20864385, -0.52408822, -0.09753053],
        [ 1.01184038, -0.87006912,  2.1229076 , -0.85689869, -0.5987338 ],
        [-0.47239892, -0.08461502, -0.95040977,  0.4138322 , -0.15321978],
        [ 2.56061181, -0.74923003, -0.55797429, -1.06868717, -0.84005389],
        [-0.66599534,  2.03006912,  0.44593042,  0.29281021,  1.33182694],
        [-0.21427034, -0.4471323 , -0.02864271, -0.43332173, -0.45022913],
        [-0.73052749,  0.03622408,  0.08087416,  2.07032068,  1.59171012],
        [ 0.68917966, -0.62839094, -0.53972148, -0.7056212 , -0.7101123 ],
        [ 0.3019868 , -0.74923003, -0.92303055, -1.03843167, -1.00712165],
        [-0.40786677,  1.06335637, -0.30243491,  2.07032068,  2.11147647],
        [-0.73052749, -0.26587366,  2.1229076 ,  2.07032068,  1.36895311],
        [ 0.62464752, -0.68881048, -0.2841821 , -0.85689869, -0.87718006],
        [-0.6014632 , -0.68881048,  0.2725287 , -0.85689869, -0.76580155],
        [ 0.04385823,  2.03006912, -0.55797429, -0.04000026, -0.63585997],
        [ 1.33450109, -0.74923003, -0.61273273, -0.7661322 , -0.7101123 ],
        [ 0.04385823, -0.62839094, -0.54884788, -0.7661322 , -0.61729688],
        [ 0.68917966, -0.68881048,  2.1229076 ,  1.92660707,  0.60786666],
        [ 0.81824395, -0.80964958, -0.35719335,  0.08102173, -0.1346567 ],
        [-0.79505963, -0.74923003, -0.08340115, -1.09894267, -0.95143239],
        [-0.1497382 ,  0.4591609 , -0.27505569,  0.35332121,  2.11147647],
        [-1.18225249, -0.62839094, -0.86827211, -0.97792068, -1.00712165],
        [-0.1497382 , -0.68881048, -0.49408944, -0.91740968, -0.95143239],
        [-0.79505963, -0.74923003, -0.76788164, -0.52408822, -0.69154922],
        [-0.1497382 ,  2.03006912,  0.32728714,  0.50459869,  1.18332227],
        [-1.11772035, -0.74923003, -0.05602193, -0.82664319, -0.80292772],
        [ 0.23745466,  1.54671274,  0.29990792, -1.06868717,  0.14378956],
        [ 1.97982252, -0.68881048, -0.40282538, -0.64511021, -0.78436464],
        [ 1.97982252,  2.03006912,  2.1229076 ,  0.68613168, -0.45022913],
        [ 1.01184038,  0.03622408,  2.1229076 ,  0.11127723,  0.70068208],
        [ 1.52809752, -0.74923003, -0.5762271 , -0.91740968, -0.95143239],
        [ 0.04385823, -0.74923003, -0.87739851, -0.22153324, -0.45022913],
        [ 0.3019868 , -0.68881048, -0.46671022, -0.7661322 , -0.85861697],
        [ 1.33450109, -0.68881048, -0.94128336, -0.94766518, -0.69154922],
        [-1.37584892, -0.56797139, -0.33894053, -0.22153324,  0.25516807],
        [-0.85959177, -0.62839094,  2.1229076 ,  2.07032068, -0.91430623],
        [ 0.36651895, -0.14503456,  1.65061607, -0.61485471, -0.63585997],
        [-2.60195964, -0.62839094,  0.90225074, -0.55434372, -0.5987338 ],
        [ 0.81824395,  1.24461501, -0.53972148, -0.10051125,  0.83062367],
        [ 0.49558323, -0.80964958, -0.7131232 , -0.79638769, -0.93286931],
        [-1.18225249, -0.14503456, -0.35719335,  0.4138322 , -0.19034595],
        [-0.27880249, -0.74923003, -0.4302046 , -0.34255523, -0.69154922],
        [ 0.68917966,  1.00293682,  0.91137715, -0.25178874,  0.06953723],
        [ 1.91529038, -0.56797139, -0.67661757, -0.55434372, -0.63585997],
        [ 0.17292252,  0.4591609 ,  0.23602307,  2.07032068,  0.12522648],
        [ 1.33450109, -0.68881048, -0.439331  , -0.91740968, -0.82149081],
        [ 1.01184038,  2.03006912,  1.9791667 , -0.07025576, -0.26459828],
        [ 1.7862261 , -0.74923003, -0.48496304, -0.85689869, -0.58017071],
        [-0.98865606, -0.56797139, -1.58925822, -0.7056212 , -0.74723847],
        [ 0.62464752,  2.03006912,  2.1229076 , -0.55434372, -0.54304455],
        [-0.73052749,  0.09664362, -0.40282538,  0.05076623, -0.52448146],
        [-0.85959177, -0.68881048, -0.83176648, -0.82664319, -0.93286931],
        [ 1.65716181, -0.3262932 , -0.94128336, -1.09894267, -0.78436464],
        [-1.50491321, -0.56797139, -0.97778899, -0.64511021, -0.84005389],
        [-1.50491321,  2.03006912,  1.19429575,  2.07032068,  2.11147647],
        [ 1.59262967, -0.62839094, -0.31156131, -0.49383272, -0.78436464],
        [ 1.7862261 ,  0.4591609 ,  0.09912698, -0.52408822, -0.19034595],
        [-2.02117035, -0.80964958,  0.64671136, -0.61485471, -0.19034595],
        [ 0.04385823,  2.03006912,  2.1229076 ,  2.07032068,  2.11147647],
        [ 0.23745466, -0.3262932 ,  2.1229076 ,  1.86609607,  2.03722414],
        [ 0.88277609,  0.51958045,  2.1229076 , -0.00974476,  0.23660498],
        [-0.6014632 , -0.62839094, -0.53972148, -0.25178874, -0.58017071],
        [ 1.01184038, -0.26587366,  1.01176762,  2.07032068,  2.11147647],
        [ 0.62464752,  2.03006912,  0.92050356,  0.56510969, -0.45022913],
        [-1.18225249, -0.02419547, -0.63098554, -0.79638769, -0.87718006],
        [ 1.01184038, -0.80964958, -0.5762271 , -0.85689869, -0.84005389],
        [ 0.10839037, -0.68881048, -0.58535351, -0.7358767 , -0.95143239],
        [ 0.49558323, -0.80964958, -0.64923835, -0.6753657 , -0.72867539],
        [-2.40836321,  2.03006912,  2.1229076 ,  2.07032068,  2.11147647],
        [-0.40786677, -0.68881048, -0.37544616, -0.7056212 , -0.30172445],
        [ 0.10839037, -0.3262932 ,  0.44593042,  2.07032068,  2.11147647],
        [ 0.43105109, -0.62839094,  0.2816551 , -0.82664319, -0.67298613],
        [ 0.68917966, -0.74923003,  0.37291917,  0.14153272, -0.15321978],
        [-2.40836321, -0.87006912,  0.93875637, -0.61485471, -0.28316137],
        [ 0.36651895, -0.80964958, -1.02342102, -1.00817618, -0.93286931],
        [-0.08520606, -0.38671275, -0.8591457 , -1.00817618, -0.85861697],
        [-1.82757392,  2.03006912,  0.17213823,  2.07032068,  1.88871946],
        [-0.1497382 ,  0.21748272,  0.39117198, -0.58459921, -0.50591838],
        [-0.79505963, -0.80964958, -0.11078037, -0.10051125, -0.65442305],
        [ 1.52809752, -0.08461502, -0.89565133, -0.91740968, -0.82149081],
        [-0.27880249, -0.80964958, -1.37935087, -0.40306623, -0.65442305],
        [ 0.62464752, -0.62839094,  0.37291917, -1.00817618, -0.89574314],
        [ 1.01184038,  0.03622408, -0.53972148, -0.10051125, -0.48735529],
        [-1.69850964, -0.68881048,  0.29990792,  0.71638717,  1.36895311],
        [ 1.33450109, -0.02419547, -0.7222496 , -0.37281073, -0.43166604],
        [ 0.36651895, -0.62839094, -0.4302046 , -0.85689869, -0.74723847],
        [-0.53693106, -0.62839094,  2.1229076 , -0.7056212 , -0.5987338 ],
        [ 1.01184038, -0.62839094, -0.74050242, -0.97792068, -0.78436464],
        [ 0.62464752, -0.3262932 , -0.49408944, -0.37281073, -0.93286931],
        [ 0.17292252,  0.64041954,  0.39117198,  0.4743432 ,  0.01384798],
        [-1.11772035, -0.38671275, -1.30633962, -0.7056212 , -0.22747212],
        [-1.50491321, -0.74923003, -0.34806694, -1.03843167, -0.80292772],
        [ 1.52809752, -0.80964958,  2.1229076 ,  1.41226361,  1.12763302],
        [-0.85959177, -0.38671275, -0.59447991, -0.58459921, -0.63585997],
        [-1.0531882 , -0.68881048, -0.53972148, -0.85689869, -0.96999548],
        [ 1.01184038,  0.21748272,  0.20864385,  0.92817566, -0.28316137],
        [ 0.23745466, -0.62839094, -0.69487039, -0.6753657 , -0.72867539],
        [ 0.81824395,  1.54671274,  0.60107933,  2.07032068,  0.71924517],
        [ 1.65716181, -0.74923003, -0.11078037, -0.91740968, -0.7101123 ],
        [-2.47289535, -0.80964958,  0.36379276, -0.31229974, -0.67298613],
        [-0.98865606, -0.74923003, -0.79526086,  0.11127723, -0.46879221],
        [-0.1497382 , -0.68881048, -1.23332837, -0.82664319, -0.80292772],
        [-0.79505963,  2.03006912,  0.2816551 ,  2.07032068,  2.11147647],
        [ 1.01184038,  2.03006912,  0.44593042,  2.07032068,  2.11147647],
        [ 1.65716181, -0.80964958,  2.1229076 ,  0.83740916,  2.11147647],
        [ 1.39903324, -0.74923003, -0.09252756, -0.64511021, -0.74723847],
        [-1.24678463, -0.80964958, -0.60360632,  1.29124162, -0.2460352 ],
        [-0.34333463, -0.02419547, -0.63098554, -0.19127775, -0.07896744],
        [ 1.01184038, -0.02419547,  2.1229076 , -0.19127775, -0.52448146],
        [-1.69850964, -0.80964958,  2.1229076 , -0.46357722, -0.5987338 ],
        [-0.73052749,  2.03006912, -0.48496304,  2.07032068,  2.11147647],
        [-0.79505963,  2.03006912, -0.50321585,  2.07032068,  2.11147647],
        [-0.1497382 , -0.68881048, -0.61273273, -0.79638769, -0.85861697],
        [-0.27880249,  0.94251728,  0.44593042,  0.59536518,  2.11147647],
        [-0.40786677,  0.39874136,  1.46808794,  0.32306571, -0.17178286],
        [ 1.33450109, -0.74923003, -0.5671007 , -0.97792068, -0.89574314],
        [-0.79505963,  2.03006912,  0.36379276,  0.29281021,  0.25516807],
        [-0.08520606, -0.68881048, -0.52146866, -0.58459921, -0.85861697],
        [-2.02117035, -0.74923003,  0.92050356, -0.94766518, -0.78436464],
        [-0.92412392, -0.68881048, -0.46671022, -0.55434372, -0.15321978],
        [ 0.88277609, -0.68881048, -1.08730586, -0.7358767 , -0.76580155]]),
 231    1
 22     1
 423    0
 116    1
 89     1
       ..
 71     1
 106    0
 270    1
 435    0
 102    1
 Name: Selector, Length: 437, dtype: int64,
 355    0
 407    1
 90     1
 402    1
 268    1
       ..
 576    1
 328    0
 334    1
 321    1
 369    1
 Name: Selector, Length: 146, dtype: int64)

In [15]:
classifier,Accuracy,report,cm,x_test,y_test=logistic(x_train,y_train,x_test)
acclog.append(Accuracy)
classifier,Accuracy,report,cm,x_test,y_test=svc(x_train,y_train,x_test)
accsvc.append(Accuracy)
classifier,Accuracy,report,cm,x_test,y_test=Decision(x_train,y_train,x_test)
accdt.append(Accuracy)
classifier,Accuracy,report,cm,x_test,y_test=random(x_train,y_train,x_test)
accrf.append(Accuracy)

result=selectk_classification(acclog,accsvc,accdt,accrf)

Fitting 5 folds for each of 3 candidates, totalling 15 fits
Fitting 5 folds for each of 6 candidates, totalling 30 fits
Fitting 5 folds for each of 6 candidates, totalling 30 fits
Fitting 5 folds for each of 6 candidates, totalling 30 fits

C:\Users\Sathish\AppData\Local\Temp\ipykernel_8640\1464381231.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  selectk_dataframe['Logistic'][idex]=acclog[number]
C:\Users\Sathish\AppData\Local\Temp\ipykernel_8640\1464381231.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  selectk_dataframe['SVC'][idex]=accsvc[number]
C:\Users\Sathish\AppData\Local\Temp\ipykernel_8640\1464381231.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  selectk_dataframe['DecisionTree'][idex]=accdt[number]
C:\Users\Sathish\AppData\Local\Temp\ipykernel_8640\1464381231.py:7: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  selectk_dataframe['RandomForest'][idex]=accrf[number]

In [16]:
result
#5

           Logistic       SVC DecisionTree RandomForest
chisquare  0.760274  0.767123     0.684932     0.746575

In [21]:
result
#3

           Logistic       SVC DecisionTree RandomForest
chisquare  0.739726  0.746575     0.671233     0.739726

In [24]:
result
#7

           Logistic       SVC DecisionTree RandomForest
chisquare  0.753425  0.760274      0.69863     0.732877

In [27]:
result
#9

           Logistic       SVC DecisionTree RandomForest
chisquare  0.712329  0.753425     0.623288     0.732877