In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("Preprocessed ILPD.csv")
dataset

,Age,Gender,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,A/G Ratio,Selector
0,65,Female,0.7,0.10,187.00,16.0,18,6.8,3.3,0.90,1
1,62,Male,5.3,2.95,481.75,64.0,100,7.5,3.2,0.74,1
2,62,Male,5.3,2.95,481.75,60.0,68,7.0,3.3,0.89,1
3,58,Male,1.0,0.40,182.00,14.0,20,6.8,3.4,1.00,1
4,72,Male,3.9,2.00,195.00,27.0,59,7.3,2.4,0.40,1
...,...,...,...,...,...,...,...,...,...,...,...
578,60,Male,0.5,0.10,481.75,20.0,34,5.9,1.6,0.37,0
579,40,Male,0.6,0.10,98.00,35.0,31,6.0,3.2,1.10,1
580,52,Male,0.8,0.20,245.00,48.0,49,6.4,3.2,1.00,1
581,31,Male,1.3,0.50,184.00,29.0,32,6.8,3.4,1.00,1
582,38,Male,1.0,0.30,216.00,21.0,24,7.3,4.4,1.50,0

In [3]:
def quanqual(dataset):
        quan=[]
        qual=[]
        for columnName in dataset.columns:
            if (dataset[columnName].dtype=='O'):
                qual.append(columnName)
            else:
                quan.append(columnName)
        return quan,qual

In [4]:
quan,qual=quanqual(dataset)

In [5]:
# How many male and female affect liver disorder?

dataset.groupby('Gender')['Selector'].sum()

Gender
Female     92
Male      324
Name: Selector, dtype: int64

In [6]:
#Who are all above 60 age affected person?

dataset.groupby(dataset['Age']>60)['Gender'].value_counts().reset_index()

     Age  Gender  count
0  False    Male    361
1  False  Female    123
2   True    Male     80
3   True  Female     19

In [8]:
#Reason for affected person?

dataset.groupby('Selector')[quan].mean()

,Age,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,A/G Ratio,Selector
Selector,,,,,,,,,,
0,41.239521,1.118563,0.390719,210.258982,32.784431,39.754491,6.543114,3.344311,1.024995,0.0
1,46.153846,2.243750,1.075962,267.717548,53.958534,74.901442,6.464904,3.060577,0.907318,1.0