1.Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

In [2]:
dataset=pd.read_csv("Indian Liver Patient.csv")

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

,Age,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,A/G Ratio,Selector,Gender_Male
0,65,0.7,0.1,187,16,18,6.8,3.3,0.90,1,0
1,62,10.9,5.5,699,64,100,7.5,3.2,0.74,1,1
2,62,7.3,4.1,490,60,68,7.0,3.3,0.89,1,1
3,58,1.0,0.4,182,14,20,6.8,3.4,1.00,1,1
4,72,3.9,2.0,195,27,59,7.3,2.4,0.40,1,1
...,...,...,...,...,...,...,...,...,...,...,...
578,60,0.5,0.1,500,20,34,5.9,1.6,0.37,2,1
579,40,0.6,0.1,98,35,31,6.0,3.2,1.10,1,1
580,52,0.8,0.2,245,48,49,6.4,3.2,1.00,1,1
581,31,1.3,0.5,184,29,32,6.8,3.4,1.00,1,1
582,38,1.0,0.3,216,21,24,7.3,4.4,1.50,2,1

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 583 entries, 0 to 582
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          583 non-null    int64
 1   TB           583 non-null    float64
 2   DB           583 non-null    float64
 3   Alkphos      583 non-null    int64
 4   Sgpt         583 non-null    int64
 5   Sgot         583 non-null    int64
 6   TP           583 non-null    float64
 7   ALB          583 non-null    float64
 8   A/G Ratio    579 non-null    float64
 9   Selector     583 non-null    int64
 10  Gender_Male  583 non-null    int64
dtypes: float64(5), int64(6)
memory usage: 50.2 KB

In [6]:
dataset.isnull().sum()

Age            0
TB             0
DB             0
Alkphos        0
Sgpt           0
Sgot           0
TP             0
ALB            0
A/G Ratio      4
Selector       0
Gender_Male    0
dtype: int64

In [7]:
dataset['A/G Ratio'].fillna(dataset['A/G Ratio'].mean,inplace=True)

C:\Users\Sathish\AppData\Local\Temp\ipykernel_9940\2121972227.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '<bound method Series.mean of 0      0.90
1      0.74
2      0.89
3      1.00
4      0.40
       ...
578    0.37
579    1.10
580    1.00
581    1.00
582    1.50
Name: A/G Ratio, Length: 583, dtype: float64>' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  dataset['A/G Ratio'].fillna(dataset['A/G Ratio'].mean,inplace=True)

In [8]:
dataset.isnull().sum()

Age            0
TB             0
DB             0
Alkphos        0
Sgpt           0
Sgot           0
TP             0
ALB            0
A/G Ratio      0
Selector       0
Gender_Male    0
dtype: int64

In [9]:
dataset['Selector']=dataset['Selector'].map({1:1,2:0})

In [10]:
dataset

,Age,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,A/G Ratio,Selector,Gender_Male
0,65,0.7,0.1,187,16,18,6.8,3.3,0.9,1,0
1,62,10.9,5.5,699,64,100,7.5,3.2,0.74,1,1
2,62,7.3,4.1,490,60,68,7.0,3.3,0.89,1,1
3,58,1.0,0.4,182,14,20,6.8,3.4,1.0,1,1
4,72,3.9,2.0,195,27,59,7.3,2.4,0.4,1,1
...,...,...,...,...,...,...,...,...,...,...,...
578,60,0.5,0.1,500,20,34,5.9,1.6,0.37,0,1
579,40,0.6,0.1,98,35,31,6.0,3.2,1.1,1,1
580,52,0.8,0.2,245,48,49,6.4,3.2,1.0,1,1
581,31,1.3,0.5,184,29,32,6.8,3.4,1.0,1,1
582,38,1.0,0.3,216,21,24,7.3,4.4,1.5,0,1